### ISSUE TITLE
feature: report and block

### ISSUE THREAD

**Issue by gbkwiatt** [paasi6666/Bot-Blocker#1]
Maybe it would be nice addition to also report and then block. Not sure if 9gag cares but maybe ?

**Comment by paasi6666** [comment]
Feature added. Would be nice if you could test it!

**Comment by gbkwiatt** [comment]
works great now, however I would select second option when reporting 
![image](https://user-images.githubusercontent.com/62710468/216840418-aa816d76-cba2-44e2-923d-4944414ac4e2.png)

Seems more apocopate. Other than that, awesome. Nice touch with different browser selection and  action options
